import { ReactLenis } from "lenis/react"; // 1. Import Lenis
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Developer Studios",
  description: "Generated by Developer Studios",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* 2. Wrap content in ReactLenis with the 'root' prop */}
        <ReactLenis root>
          {/* 🔥 Global Toaster for notifications */}
          <Toaster position="top-right" reverseOrder={false} />

          {children}
        </ReactLenis>
        
      </body>
    </html>
  );
}